controller_list:
  - name: fake_thumb_controller
    joints:
      - servo0
      - servo1
  - name: fake_finger1_controller
    joints:
      - servo2
      - servo3
  - name: fake_finger2_controller
    joints:
      - servo4
      - servo5
  - name: fake_finger3_controller
    joints:
      - servo6
      - servo7
  - name: fake_finger4_controller
    joints:
      - servo8
      - servo9